"""Command-line entrypoint.

Usage:
    release-notes-agent owner/repo --version v1.2.0 [--base v1.1.0] [--out dir]
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

from .collector import collect_changes
from .github_client import GitHubClient, GitHubError
from .summarizer import summarize


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="release-notes-agent",
        description="Draft release notes + social posts from merged PRs and commits.",
    )
    p.add_argument("repo", help="GitHub repository in owner/name form")
    p.add_argument("--version", required=True, help="Version being released, e.g. v1.2.0")
    p.add_argument("--base", help="Tag/ref to diff from (default: latest release)")
    p.add_argument("--head", help="Branch/ref to release from (default: default branch)")
    p.add_argument("--out", default="release-notes-output", help="Output directory")
    p.add_argument(
        "--token",
        default=os.environ.get("GITHUB_TOKEN"),
        help="GitHub token (default: $GITHUB_TOKEN)",
    )
    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)

    if "/" not in args.repo:
        print("error: repo must be in owner/name form", file=sys.stderr)
        return 2

    client = GitHubClient(token=args.token)
    try:
        changeset = collect_changes(client, args.repo, base_ref=args.base, head_ref=args.head)
    except GitHubError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    if changeset.is_empty:
        print(f"No changes found in {args.repo} since {changeset.base_ref or 'the beginning'}.")
        return 0

    print(
        f"Found {len(changeset.changes)} changes in {args.repo} "
        f"since {changeset.base_ref or 'the beginning'}."
    )

    content = summarize(changeset, args.version)

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    (out / "RELEASE_NOTES.md").write_text(content.release_notes + "\n")
    (out / "tweet.txt").write_text(content.tweet + "\n")
    (out / "linkedin.txt").write_text(content.linkedin + "\n")

    print(f"Wrote release notes, tweet, and LinkedIn post to {out}/ "
          f"(generated by: {content.generated_by})")

    # Expose outputs to later GitHub Actions steps
    gh_output = os.environ.get("GITHUB_OUTPUT")
    if gh_output:
        with open(gh_output, "a") as f:
            f.write(f"notes-file={out / 'RELEASE_NOTES.md'}\n")
            f.write(f"tweet-file={out / 'tweet.txt'}\n")
            f.write(f"linkedin-file={out / 'linkedin.txt'}\n")
            f.write(f"generated-by={content.generated_by}\n")

    print("\n--- RELEASE_NOTES.md ---\n")
    print(content.release_notes)
    print("\n--- tweet.txt ---\n")
    print(content.tweet)
    return 0


if __name__ == "__main__":
    sys.exit(main())
